---

telegraf_interval: "30s"
telegraf_prometheus_client_listen: ":9273"
telegraf_prometheus_client_path: "/metrics"
telegraf_prometheus_client_expiration_interval: "60s"
telegraf_prometheus_client_basic_username: "prometheus"
telegraf_prometheus_client_basic_password: "prometheus"
