---

kind: pipeline
type: docker
name: deploy

steps:
  - name: deploy test
    image: python:3.9-slim-bullseye
    environment:
      VAULT_PASS:
        from_secret: "vault_pass"
      SSH_KEY:
        from_secret: "ssh_key"
    commands:
      - echo $${VAULT_PASS} > .vault_pass.txt
      - echo -e $${SSH_KEY} > id_ssh_key
      - chmod 600 id_ssh_key
      - apt update && apt install -y git
      - python3 -m pip install -r requirements.txt
      - ansible-galaxy install -r requirements.yml
      - ansible-playbook --key-file id_ssh_key --user droneci --inventory inventory/test.yml playbooks/wh_api.yml
      - ansible-playbook --key-file id_ssh_key --user droneci --inventory inventory/prod.yml playbooks/wh_api.yml
