---

kind: pipeline
type: docker
name: deploy

steps:
  - name: deploy
    image: againddm/ci-ansible:5.8.0
    user: root
    environment:
      VAULT_PASS:
        from_secret: "vault_pass"
      SSH_KEY:
        from_secret: "ssh_key"
    commands:
      - echo $${VAULT_PASS} > .vault_pass.txt
      - eval $(ssh-agent)
      - echo $${SSH_KEY} | ssh-add -
      - ansible-galaxy install -r requirements.yml
      - ansible-playbook --tags deploy-wh-api --user droneci --inventory inventory/prod.yml playbooks/prod.yml
