---

all:
  hosts:
    test-server:
  children:
    dotnet_backends:
      children:
        wh_api:
          hosts:
            prod-server:
        questionnaire_bot:
          hosts:
            prod-server:
    wh_database_mysql:
      hosts:
        prod-server:
    proxy:
      hosts:
        prod-server:
