---

questionnaire_bot_user: "questionnaire-bot"
questionnaire_bot_group: "questionnaire-bot"

questionnaire_bot_systemd_dir: "/etc/systemd/system"
questionnaire_bot_limit_no_file: 256
questionnaire_bot_restart_sec: 10
questionnaire_bot_timeout_stop_sec: 30

questionnaire_bot_build_directory: "/tmp/questionnaire-bot"
questionnaire_bot_app_directory: "/opt/questionnaire-bot"
questionnaire_bot_build_configuration: "Release"
questionnaire_bot_main_csproj_subpath: "RQ.Bot/RQ.Bot.csproj"
questionnaire_bot_repository_url: "https://github.com/kenoma/Refugee.Questionnaire.git"
questionnaire_bot_entrypoint_dll: "RQ.Bot.dll"
questionnaire_bot_repository_version: "master"

questionnaire_bot_instances:
  - systemd_unit: "questionnaire-bot-9031.service"
    syslog_identifer: "questionnaire-bot-9031"
    working_directory: "/opt/questionnaire-bot/instances/9031"
    telegram_token: "xxxxxxx:yyyyyyyyyyyyy"
    urls: "http://localhost:9031"
    db_path: "/opt/questionnaire-bot/instances/9031/db"
    quest_path: "/opt/questionnaire-bot/instances/9031/quest.csv"
    quest_csv_src: "quest9031.csv"
