---

core_api_user: "core-api"
core_api_group: "core-api"
core_api_systemd_dir: "/etc/systemd/system"
core_api_systemd_unit: "core-api.service"
core_api_working_directory: "/opt/core-api"
core_api_build_directory: "/tmp/core-api"
core_api_syslog_identifer: "core-api"
core_api_limit_no_file: 4096
core_api_restart_sec: 10
core_api_timeout_stop_sec: 90
