---

- name: set hostname
  hostname:
    name: "{{ inventory_hostname }}"
  become: true

- name: update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day
  become: true

- name: install common packages
  apt:
    pkg: "{{ common_apt_packages }}"
    state: present
    install_recommends: no
    update_cache: no
  become: true

- name: upgrade pip
  pip:
    name: "{{ item }}"
    extra_args: --upgrade
  with_items: "{{ common_pip_packages }}"

- name: sudo nopasswd validate
  copy:
    src: sudoers
    dest: /etc/sudoers.edit
    validate: /usr/sbin/visudo -csf %s
  become: true

- name: sudo nopasswd apply
  copy:
    src: /etc/sudoers.edit
    dest: /etc/sudoers
    validate: /usr/sbin/visudo -csf %s
    remote_src: true
  become: true

- name: clean sudoers.edit
  file:
    path: /etc/sudoers.edit
    state: absent
  become: true

- name: manage users
  include_tasks: "manage_user.yml"
  with_items: "{{ common_users }}"

- name: remove revoked users
  user:
    name: "{{ item }}"
    state: "absent"
  with_items: "{{ common_revoked_users }}"
  become: true

- name: sshd config change
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
  become: true
  notify:
    - restart_sshd

- name: sshd config change
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
  become: true
  notify:
    - restart_sshd
