---

- name: create questionnaire_bot_group
  group:
    name: "{{ questionnaire_bot_group }}"
    state: present
  become: true

- name: create questionnaire_bot_user
  user:
    name: "{{ questionnaire_bot_user }}"
    comment: "questionnaire_bot_user"
    group: "{{ questionnaire_bot_group }}"
    shell: /sbin/nologin
    state: present
  become: true

- name: install git
  apt:
    pkg:
      - git
    state: present
    install_recommends: no
    update_cache: yes
    cache_valid_time: 86400 # One day
  become: true

- name: install pygit
  pip:
    name: pygit
    extra_args: --upgrade

- name: enshure build directory not exists
  file:
    path: "{{ questionnaire_bot_build_directory }}"
    state: "absent"
  become: true

- name: clone sources
  git:
    repo: "{{ questionnaire_bot_repository_url }}"
    dest: "{{ questionnaire_bot_build_directory }}"
    single_branch: yes
    version: "{{ questionnaire_bot_repository_version }}"
    clone: yes
    accept_newhostkey: yes
    depth: 1
  become: false

- name: clear locks
  file:
    path: "/tmp/NuGetScratch"
    state: "absent"
  become: true

- name: build application
  command: |
    /usr/bin/dotnet publish
    --output {{ questionnaire_bot_build_directory }}/bin
    --configuration {{ questionnaire_bot_build_configuration }}
    {{ questionnaire_bot_build_directory }}/{{ questionnaire_bot_main_csproj_subpath }}
  args:
    chdir: "{{ questionnaire_bot_build_directory }}"
  become: false

- name: create app directory
  file:
    path: "{{ questionnaire_bot_app_directory }}"
    state: "directory"
    recurse: yes
    owner: "{{ questionnaire_bot_user }}"
    group: "{{ questionnaire_bot_group }}"
    mode: "0755"
  become: true

- name: ls build results
  command: "ls {{ questionnaire_bot_build_directory }}/bin"
  register: "build_results"

- name: copy files to app directory
  copy:
    remote_src: true
    src: "{{ questionnaire_bot_build_directory }}/bin/{{ item }}"
    dest: "{{ questionnaire_bot_app_directory }}"
    owner: "{{ questionnaire_bot_user }}"
    group: "{{ questionnaire_bot_group }}"
    mode: "0555"
    backup: no
    force: yes
  with_items: "{{ build_results.stdout_lines }}"
  become: true
  notify:
    - restart_all_instances

- name: deploy instances
  include_tasks: deploy_instance.yml
  no_log: true
  with_items: "{{ questionnaire_bot_instances }}"
  loop_control:
    loop_var: "instance"

- name: clean build directory
  file:
    path: "{{ questionnaire_bot_build_directory }}"
    state: "absent"
  become: true
