---

- name: common
  hosts:
    - all
  roles:
    - common
  tags: common

- name: mysql
  hosts:
    - wh_database_mysql
  roles:
    - wh-database-mysql
  tags: wh-database-mysql
  become: true

- name: install-dotnet-core
  hosts:
    - dotnet_backends
  roles:
    - dotnet-core
  tags:
    - dotnet-core
    - deploy-wh-api
    - deploy-questionnaire-bot

- name: deploy-wh-api
  hosts:
    - wh_api
  roles:
    - deploy-wh-api
  tags:
    - deploy-wh-api

- name: nextcloud
  hosts:
    - nextcloud
  roles:
    - nextcloud
  tags:
    - nextcloud
  become: true

- name: proxy
  hosts:
    - proxy
  roles:
    - proxy
  tags:
    - proxy
  become: true

- name: telegraf
  hosts:
    - all
  roles:
    - telegraf
  tags: telegraf
  become: true
