---

- name: common
  hosts:
    - wh_api
    - wh_database_mysql
  roles:
    - common
  tags: common

- name: mysql
  hosts:
    - wh_database_mysql
  roles:
    - mysql
  tags: mysql
  become: true

- name: deploy-wh-api
  hosts:
    - wh_api
  roles:
    - deploy-wh-api
  tags: deploy-wh-api

- name: proxy
  hosts:
    - proxy
  roles:
    - proxy
  tags: proxy
  become: true
